### ISSUE TITLE
Tile Prompter - McBoaty [2/3] v4 & v5 unable to delete node, causing other issues

### ISSUE THREAD

**Issue by ReduxST** [MaraScott/ComfyUI_MaraScott_Nodes#170]
## Problem Description
When attempting to place the Tile Prompter node into a workflow, the webpage freezes temporarily or becomes completely unresponsive. After being successfully placed in a workflow it can't be deleted. Trying to change workflow or undo its placement or any subsequent changes results in an error:

Loading aborted due to error reloading workflow data

RangeError: Maximum call stack size exceeded

Log:
```
RangeError: Maximum call stack size exceeded
    at Set.delete (<anonymous>)
    at ComfyNode.onRemoved (https://[redacted]:47733/assets/index-B6dYHNhg.js:76301:26)
    at ComfyNode.onRemoved (https://[redacted]:47733/assets/index-B6dYHNhg.js:76302:16)
    at ComfyNode.onRemoved (https://[redacted]:47733/assets/index-B6dYHNhg.js:76302:16)
    at ComfyNode.onRemoved (https://[redacted]:47733/assets/index-B6dYHNhg.js:76302:16)
    at ComfyNode.onRemoved (https://[redacted]:47733/assets/index-B6dYHNhg.js:76302:16)
    at ComfyNode.onRemoved (https://[redacted]:47733/assets/index-B6dYHNhg.js:76302:16)
    at ComfyNode.onRemoved (https://[redacted]:47733/assets/index-B6dYHNhg.js:76302:16)
    at ComfyNode.onRemoved (https://[redacted]:47733/assets/index-B6dYHNhg.js:76302:16)
    at ComfyNode.onRemoved (https://[redacted]:47733/assets/index-B6dYHNhg.js:76302:16)
```

### Software Versions
- OS: Ubuntu 22.04.4 LTS (jammy)
- Python: 3.10.12 [GCC 11.4.0]
- PyTorch: 2.4.1+cu121
- CUDA: 12.4 (Driver Version: 550.90.07)

### Hardware Specifications
- CPU: AMD EPYC 7402P 24-Core Processor
  - Cores: 24 (48 threads)
  - Architecture: x86_64
  - Max Frequency: 2.8 GHz
  - Cache: 128 MiB L3, 12 MiB L2

- GPU: NVIDIA GeForce RTX 3090
  - VRAM: 24576 MiB
  - CUDA Enabled: Yes
  - CUDA Version: 12.1.105

- Memory:
  - Total RAM: 251 GB
  - Available: 228 GB
  - Swap: 31 GB

### Environment Details
- CUDA is available and functional
- Running in a docker environment on a cloud server

### List of other nodes installed
```
    "https://github.com/ltdrdata/ComfyUI-Manager"
    "https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved"
    "https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet"
    "https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite"
    "https://github.com/cubiq/ComfyUI_IPAdapter_plus"
    "https://github.com/aianimation55/ComfyUI-FatLabels"
    "https://github.com/MaraScott/ComfyUI_MaraScott_Nodes"
    "https://github.com/crystian/ComfyUI-Crystools"
    "https://github.com/PowerHouseMan/ComfyUI-AdvancedLivePortrait"
    "https://github.com/rgthree/rgthree-comfy"
    "https://github.com/chrisgoringe/cg-use-everywhere"
    "https://github.com/ltdrdata/ComfyUI-Impact-Pack"
    "https://github.com/WASasquatch/was-node-suite-comfyui"
    "https://github.com/pythongosssss/ComfyUI-Custom-Scripts"
    "https://github.com/Smirnov75/ComfyUI-mxToolkit"
    "https://github.com/jags111/efficiency-nodes-comfyui"
    "https://github.com/XLabs-AI/x-flux-comfyui"
    "https://github.com/M1kep/ComfyLiterals"
    "https://github.com/Extraltodeus/ComfyUI-AutomaticCFG"
    "https://github.com/kijai/ComfyUI-KJNodes"
    "https://github.com/storyicon/comfyui_segment_anything"
    "https://github.com/neverbiasu/ComfyUI-SAM2"
    "https://github.com/TripleHeadedMonkey/ComfyUI_MileHighStyler"
    "https://github.com/cubiq/ComfyUI_essentials"
    "https://github.com/Fannovel16/comfyui_controlnet_aux"
    "https://github.com/comfyanonymous/ComfyUI_bitsandbytes_NF4"
    "https://github.com/city96/ComfyUI-GGUF"
    "https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes"
    "https://github.com/Gourieff/comfyui-reactor-node"
    "https://github.com/shiimizu/ComfyUI-PhotoMaker-Plus"
    "https://github.com/1038lab/ComfyUI-OmniGen"
    "https://github.com/yolain/ComfyUI-Easy-Use"
    "https://github.com/Jonseed/ComfyUI-Detail-Daemon"
    "https://github.com/bvhari/ComfyUI_SUNoise"
    "https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes"
    "https://github.com/Extraltodeus/sigmas_tools_and_the_golden_scheduler"
    "https://github.com/giriss/comfy-image-saver"
    "https://github.com/ssitu/ComfyUI_UltimateSDUpscale"
    "https://github.com/erosDiffusion/ComfyUI-enricos-nodes"
    "https://github.com/john-mnz/ComfyUI-Inspyrenet-Rembg"
```
### List of python packages and their version
```
absl-py                           2.1.0
accelerate                        1.1.1
addict                            2.4.0
aggdraw                           1.3.19
aiohappyeyeballs                  2.4.3
aiohttp                           3.10.10
aioice                            0.9.0
aiortc                            1.9.0
aiosignal                         1.3.1
albucore                          0.0.16
albumentations                    1.4.15
annotated-types                   0.7.0
anthropic                         0.34.2
antlr4-python3-runtime            4.9.3
anyio                             4.6.2.post1
APScheduler                       3.10.4
arrow                             1.3.0
asttokens                         2.4.1
async-timeout                     4.0.3
attrs                             24.2.0
av                                12.3.0
backoff                           2.2.1
beautifulsoup4                    4.12.3
binaryornot                       0.4.4
bitsandbytes                      0.44.1
blend_modes                       2.2.0
blind-watermark                   0.4.4
boto3                             1.35.60
botocore                          1.35.63
cachetools                        5.5.0
certifi                           2024.8.30
cffi                              1.17.1
chardet                           5.2.0
charset-normalizer                3.4.0
click                             8.1.7
clip-interrogator                 0.6.0
cmake                             3.31.0.1
color-matcher                     0.5.0
colorama                          0.4.6
coloredlogs                       15.0.1
colorlog                          6.9.0
colour-science                    0.4.6
comm                              0.2.2
commonmark                        0.9.1
contourpy                         1.3.1
cookiecutter                      2.6.0
cryptography                      43.0.3
cssselect2                        0.7.0
cstr                              0.1.0
cycler                            0.12.1
Cython                            3.0.11
dataclasses-json                  0.6.7
ddt                               1.7.2
debugpy                           1.8.7
decorator                         5.1.1
deepdiff                          8.0.1
defusedxml                        0.7.1
Deprecated                        1.2.14
diffusers                         0.31.0
dill                              0.3.8
distro                            1.9.0
dnspython                         2.7.0
docker                            7.1.0
docker-pycreds                    0.4.0
docopt                            0.6.2
docstring_parser                  0.16
docutils                          0.21.2
easydict                          1.13
einops                            0.8.0
embreex                           2.17.7.post5
eval_type_backport                0.2.0
exceptiongroup                    1.2.2
executing                         2.1.0
fairscale                         0.4.0
fastapi                           0.110.3
ffmpy                             0.3.0
filelock                          3.13.1
flatbuffers                       24.3.25
flet                              0.24.1
flet-core                         0.24.1
flet-runtime                      0.24.1
fonttools                         4.55.0
frozenlist                        1.5.0
fsspec                            2024.2.0
ftfy                              6.3.1
fvcore                            0.1.5.post20221221
gdown                             5.2.0
gguf                              0.10.0
gitdb                             4.0.11
GitPython                         3.1.43
google-ai-generativelanguage      0.6.10
google-api-core                   2.23.0
google-api-python-client          2.153.0
google-auth                       2.36.0
google-auth-httplib2              0.2.0
google-crc32c                     1.6.0
google-generativeai               0.8.3
googleapis-common-protos          1.66.0
GPUtil                            1.4.0
groq                              0.12.0
grpcio                            1.68.0
grpcio-status                     1.68.0
h11                               0.14.0
httpcore                          1.0.6
httplib2                          0.22.0
httptools                         0.6.4
httpx                             0.27.2
huggingface-hub                   0.26.2
humanfriendly                     10.0
hydra-core                        1.3.2
idna                              3.10
ifaddr                            0.2.0
imageio                           2.36.0
imageio-ffmpeg                    0.5.1
img2texture                       1.0.6
importlib_metadata                8.5.0
inference-cli                     0.27.0
inference-gpu                     0.27.0
iniconfig                         2.0.0
insightface                       0.7.3
iopath                            0.1.10
ipykernel                         6.29.5
ipython                           8.28.0
ipywidgets                        8.1.5
jax                               0.4.35
jaxlib                            0.4.35
jedi                              0.19.1
Jinja2                            3.1.3
jiter                             0.7.1
jmespath                          1.0.1
joblib                            1.4.2
jsonschema                        4.23.0
jsonschema-specifications         2024.10.1
jupyter_client                    8.6.3
jupyter_core                      5.7.2
jupyterlab_widgets                3.0.13
kiwisolver                        1.4.7
kornia                            0.7.4
kornia_rs                         0.1.7
lark-parser                       0.12.0
lazy_loader                       0.4
llvmlite                          0.43.0
lmdb                              1.5.1
loguru                            0.7.2
lxml                              5.3.0
manifold3d                        2.5.1
mapbox_earcut                     1.0.2
markdown-it-py                    3.0.0
MarkupSafe                        2.1.5
marshmallow                       3.23.1
matplotlib                        3.9.2
matplotlib-inline                 0.1.7
matrix-client                     0.4.0
mdurl                             0.1.2
mediapipe                         0.10.18
ml_dtypes                         0.5.0
mpmath                            1.3.0
mss                               10.0.0
multidict                         6.1.0
mypy-extensions                   1.0.0
nest-asyncio                      1.6.0
networkx                          3.2.1
numba                             0.60.0
numpy                             1.26.4
nvidia-cublas-cu12                12.1.3.1
nvidia-cuda-cupti-cu12            12.1.105
nvidia-cuda-nvrtc-cu12            12.1.105
nvidia-cuda-runtime-cu12          12.1.105
nvidia-cudnn-cu12                 9.1.0.70
nvidia-cufft-cu12                 11.0.2.54
nvidia-curand-cu12                10.3.2.106
nvidia-cusolver-cu12              11.4.5.107
nvidia-cusparse-cu12              12.1.0.106
nvidia-nccl-cu12                  2.20.5
nvidia-nvjitlink-cu12             12.1.105
nvidia-nvtx-cu12                  12.1.105
oauthlib                          3.2.2
omegaconf                         2.3.0
onnx                              1.17.0
onnxruntime                       1.20.0
onnxruntime-gpu                   1.19.2
open_clip_torch                   2.29.0
openai                            1.54.4
opencv-contrib-python             4.10.0.84
opencv-python                     4.10.0.84
opencv-python-headless            4.10.0.84
opt_einsum                        3.4.0
orderly-set                       5.2.2
packaging                         24.2
pandas                            2.2.3
parso                             0.8.4
peft                              0.13.2
pexpect                           4.9.0
piexif                            1.1.3
pilgram                           1.2.1
pillow                            10.4.0
pip                               22.0.2
pixeloe                           0.0.10
platformdirs                      4.3.6
pluggy                            1.5.0
pooch                             1.8.2
portalocker                       2.10.1
prettytable                       3.12.0
prometheus_client                 0.21.0
prometheus-fastapi-instrumentator 6.0.0
prompt_toolkit                    3.0.48
propcache                         0.2.0
proto-plus                        1.25.0
protobuf                          5.28.3
psd-tools                         1.10.2
psutil                            6.1.0
ptyprocess                        0.7.0
pure_eval                         0.2.3
py-cpuinfo                        9.0.0
pyasn1                            0.6.1
pyasn1_modules                    0.4.1
pybase64                          1.0.2
pycollada                         0.8
pycparser                         2.22
pydantic                          2.9.2
pydantic_core                     2.23.4
pydantic-settings                 2.6.1
pydot                             2.0.0
pyee                              12.0.0
PyGithub                          2.5.0
Pygments                          2.18.0
PyJWT                             2.9.0
pylibsrtp                         0.10.0
PyMatting                         1.1.12
PyNaCl                            1.5.0
pynvml                            11.5.3
pyOpenSSL                         24.2.1
pyparsing                         3.2.0
pypng                             0.20220715.0
PySocks                           1.7.1
pytest                            8.3.3
python-dateutil                   2.9.0.post0
python-dotenv                     1.0.1
python-slugify                    8.0.4
pytz                              2024.2
PyWavelets                        1.7.0
PyYAML                            6.0.2
pyzbar                            0.1.9
pyzmq                             26.2.0
qrcode                            7.4.2
redis                             5.0.8
referencing                       0.35.1
regex                             2024.11.6
rembg                             2.0.59
repath                            0.9.0
reportlab                         4.2.5
requests                          2.32.3
requests-file                     2.1.0
requests-toolbelt                 1.0.0
rf-clip                           1.1
rich                              13.0.1
rpds-py                           0.21.0
rsa                               4.9
Rtree                             1.3.0
s3transfer                        0.10.3
safetensors                       0.4.5
scikit-image                      0.24.0
scikit-learn                      1.5.2
scipy                             1.14.1
seaborn                           0.13.2
segment-anything                  1.0
sentencepiece                     0.2.0
sentry-sdk                        2.18.0
setproctitle                      1.3.3
setuptools                        75.5.0
shapely                           2.0.6
shellingham                       1.5.4
shtab                             1.7.1
simpleeval                        1.0.3
simsimd                           6.0.5
six                               1.16.0
smmap                             5.0.1
sniffio                           1.3.1
sounddevice                       0.5.1
soundfile                         0.12.1
soupsieve                         2.6
spandrel                          0.4.0
stack-data                        0.6.3
starlette                         0.37.2
stringzilla                       3.10.10
structlog                         24.4.0
supervision                       0.22.0
svg.path                          6.3
svglib                            1.5.1
sympy                             1.13.1
tabulate                          0.9.0
termcolor                         2.5.0
text-unidecode                    1.3
threadpoolctl                     3.5.0
tifffile                          2024.9.20
timm                              0.6.13
tinycss2                          1.4.0
tldextract                        5.1.3
tokenizers                        0.20.3
tomli                             2.1.0
torch                             2.4.1+cu121
torchaudio                        2.4.1+cu121
torchscale                        0.3.0
torchsde                          0.2.6
torchvision                       0.19.1+cu121
tornado                           6.4.1
tqdm                              4.67.0
traitlets                         5.14.3
trampoline                        0.1.2
transformers                      4.46.2
transparent-background            1.3.3
trimesh                           4.5.2
triton                            3.0.0
typer                             0.12.5
typer-config                      1.4.2
types-python-dateutil             2.9.0.20241003
typing_extensions                 4.12.2
typing-inspect                    0.9.0
tyro                              0.8.5
tzdata                            2024.2
tzlocal                           5.2
ultralytics                       8.3.32
ultralytics-thop                  2.0.11
uritemplate                       4.1.1
urllib3                           1.26.20
uvicorn                           0.32.0
uvloop                            0.21.0
vhacdx                            0.0.8.post1
wandb                             0.18.7
watchdog                          4.0.2
watchfiles                        0.24.0
wcwidth                           0.2.13
webencodings                      0.5.1
websockets                        13.1
wget                              3.2
wheel                             0.45.0
widgetsnbextension                4.0.13
wrapt                             1.16.0
xatlas                            0.0.9
xformers                          0.0.28.post1
xxhash                            3.5.0
yacs                              0.1.8
yapf                              0.43.0
yarl                              1.17.1
zipp                              3.21.0
zxing-cpp                         2.2.0
```

### Tried solutions (issue persists for all)
Restarting ComfyUI
Disabling all other custom nodes
"Update All"

### Current workarounds
- Disabling MaraScott nodes, make necessary changes, re-enable MaraScott nodes

**Comment by MaraScott** [comment]
Hi, I noticed my nodes are no more responsive as it should, I'm under investigating cause AnyBus and McBoaty Tile Prompter are making bugs, I'll update you asap

**Comment by MaraScott** [comment]
Hi, thanx to bring that up, the number of max tile was to important for Js which brought that issue, I've reverted to max 64 tiles.
https://github.com/MaraScott/ComfyUI_MaraScott_Nodes/pull/173

McBoaty in in the middle of a revamp to V6 which will allow to manage more than 64 tiles but won't bring that issue

sorry for the error
