### ISSUE TITLE
Crash due VAEDecodeTiled .. unsure how to fix.

### ISSUE THREAD

**Issue by Mescalamba** [MaraScott/ComfyUI_MaraScott_Nodes#178]
MaraScott][Refining 1/1] tile 16/16
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:06<00:00,  1.33s/it]
[MaraScott][VAEDecodingTiled 1/1] tile 1/16
!!! Exception during processing !!! VAEDecodeTiled.decode() takes 4 positional arguments but 5 were given
Traceback (most recent call last):
  File "C:\Programs\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programs\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programs\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Programs\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programs\ComfyUI\custom_nodes\ComfyUI_MaraScott_Nodes\py\nodes\UpscalerRefiner\McBoaty_v3.py", line 157, in fn
    output_image, output_tiles, output_prompts = self.upscale_refine(current_image, f"{index + 1}/{self.PARAMS.max_iterations}")
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programs\ComfyUI\custom_nodes\ComfyUI_MaraScott_Nodes\py\nodes\UpscalerRefiner\McBoaty_v3.py", line 387, in upscale_refine
    output = (nodes.VAEDecodeTiled().decode(self.KSAMPLER.vae, latent_output, self.KSAMPLER.tile_size_vae, self.KSAMPLER.tile_size_vae // 4)[0].unsqueeze(0))[0]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: VAEDecodeTiled.decode() takes 4 positional arguments but 5 were given

**Comment by Mescalamba** [comment]
Thats v3, v5 doesnt work either. Hm.. sad.

**Comment by Mescalamba** [comment]
"Fixed" by changing line 627 in McBoaty_v5 to

                    output = (nodes.VAEDecodeTiled().decode(self.KSAMPLER.vae, latent_output, self.KSAMPLER.tile_size_vae)[0].unsqueeze(0))[0]
                    
It works now, altho not sure if its correct fix, will play with it.

**Comment by ReduxST** [comment]
I've had the same issue and I believe it can only occur when using tiled vae encoding as opposed to standard.  The option to switch is located in the upscaler node or the large refiner node. Unless you expressly need tiled vae encode you can switch to standard as a temporary fix as well.

**Comment by MaraScott** [comment]
@Mescalamba and @ReduxST , thanks for following up.
the issues occurs cause the VAEDecodeTiled has been updated.

McBoaty_v5 has been updated accordingly but not v3 that will be soon retired.

do you use the latest version ? if not please upgrade and let me know but I would advise to use McBoaty_v6 instead.

I close the issue, if you need further assistance let me know

**Comment by MaraScott** [comment]
Hmmm, I ve fixed it again, apparently I inherited the bug from a previous version, please make sure to get latest version
