### ISSUE TITLE
Error executing Large Refiner McBoaty v2

### ISSUE THREAD

**Issue by gonzalu** [MaraScott/ComfyUI_MaraScott_Nodes#52]
I am getting this error on a fairly fresh install of ComfyUI. 

```
!!! Exception during processing!!! module 'comfy_extras' has no attribute 'nodes_upscale_model'
Traceback (most recent call last):
  File "E:\dev\ComfyUI_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\dev\ComfyUI_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\dev\ComfyUI_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\dev\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI_MaraScott_Nodes\py\nodes\UpscalerRefiner\McBoaty_v2.py", line 167, in fn
    upscale_model = comfy_extras.nodes_upscale_model.UpscaleModelLoader.load_model(comfy_extras.nodes_upscale_model.UpscaleModelLoader, upscale_model_name)[0]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'comfy_extras' has no attribute 'nodes_upscale_model'

```
## I have the following custom nodes installed. 

![image](https://github.com/davask/ComfyUI_MaraScott_Nodes/assets/32348862/c66c3721-5ae6-41ec-a1cd-c241d773154a)

Here is my console prior to running the workflow

```
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-05-14 14:06:32.826101
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: E:\dev\ComfyUI_portable\python_embeded\python.exe
** Log path: E:\dev\ComfyUI_portable\comfyui.log
[Maras IT] Initialization

Prestartup times for custom nodes:
   0.0 seconds: E:\dev\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI_MaraScott_Nodes
   0.2 seconds: E:\dev\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24563 MB, total RAM 65478 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### Loading: ComfyUI-Manager (V2.33)
### ComfyUI Revision: 2180 [2de3b69b] | Released on '2024-05-13'
### Loading: Save img prompt
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
### [START] ComfyUI AlekPet Nodes ###
Node -> ArgosTranslateNode [Loading]
Node -> DeepTranslatorNode [Loading]
Node -> ExtrasNode [Loading]
Node -> GoogleTranslateNode [Loading]
Node -> PainterNode [Loading]
Node -> PoseNode [Loading]
### [END] ComfyUI AlekPet Nodes ###
[Maras IT] Loaded
[comfy_mtb] | INFO -> loaded 73 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (5) could not be loaded. This can be ignored, but go to http://127.0.0.1:9188/mtb if you want more information.

Import times for custom nodes:
   0.0 seconds: E:\dev\ComfyUI_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\dev\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI-SaveImgPrompt
   0.0 seconds: E:\dev\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI_YFG_Comical
   0.1 seconds: E:\dev\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI_MaraScott_Nodes
   0.2 seconds: E:\dev\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.3 seconds: E:\dev\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.7 seconds: E:\dev\ComfyUI_portable\ComfyUI\custom_nodes\comfy_mtb
   5.0 seconds: E:\dev\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet

Starting server

To see the GUI go to: http://127.0.0.1:9188
```

## and here is the workflow
[Error_workflow.json](https://github.com/davask/ComfyUI_MaraScott_Nodes/files/15312380/Error_workflow.json)

**Comment by MaraScott** [comment]
Hi,

have you updated your ComfyUI insatll lately ?

you should find the missing module under /ComfyUI/comfy_extras/nodes_upscale_model.py

![image](https://github.com/MaraScott/ComfyUI_MaraScott_Nodes/assets/482210/bb40581d-c0a3-45d4-9db6-1d7a139aada7)
