### ISSUE TITLE
Error no module named blend_modes

### ISSUE THREAD

**Issue by thjan** [MaraScott/ComfyUI_MaraScott_Nodes#60]
Hi, 
 It seems that this package takes precedence over `was-node-suite-comfyui` when installing dependencies with `comfy-cli`: 
 `comfy node install-deps --workflow <myworkflow.json>` will now install `ComfyUI_MaraScott_Nodes` rather than the WAS package because this package includes several others.

 The error encountered is: 
 ```
Traceback (most recent call last):
  File "/home/user/repos/ComfyUI/nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/repos/ComfyUI/custom_nodes/ComfyUI_MaraScott_Nodes/__init__.py", line 55, in <module>
    from .MaraScott_Nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS, WEB_DIRECTORY
  File "/home/user/repos/ComfyUI/custom_nodes/ComfyUI_MaraScott_Nodes/MaraScott_Nodes.py", line 17, in <module>
    from .py.nodes.KSampler.InpaintingTileByMask_v1 import KSampler_setInpaintingTileByMask_v1, KSampler_pasteInpaintingTileByMask_v1
  File "/home/user/repos/ComfyUI/custom_nodes/ComfyUI_MaraScott_Nodes/py/nodes/KSampler/InpaintingTileByMask_v1.py", line 19, in <module>
    from ...vendor.ComfyUI_LayerStyle.py.image_blend_v2 import ImageBlendV2, chop_mode_v2
  File "/home/user/repos/ComfyUI/custom_nodes/ComfyUI_MaraScott_Nodes/py/vendor/ComfyUI_LayerStyle/py/image_blend_v2.py", line 1, in <module>
    from .imagefunc import torch, Image, tensor2pil, pil2tensor, chop_mode_v2, chop_image_v2
  File "/home/user/repos/ComfyUI/custom_nodes/ComfyUI_MaraScott_Nodes/py/vendor/ComfyUI_LayerStyle/py/imagefunc.py", line 40, in <module>
    from .blendmodes import *
  File "/home/user/repos/ComfyUI/custom_nodes/ComfyUI_MaraScott_Nodes/py/vendor/ComfyUI_LayerStyle/py/blendmodes.py", line 10, in <module>
    from blend_modes import difference, normal, screen, soft_light, lighten_only, dodge,   \
ModuleNotFoundError: No module named 'blend_modes'

Cannot import /home/user/repos/ComfyUI/custom_nodes/ComfyUI_MaraScott_Nodes module for custom nodes: No module named 'blend_modes
```
blend_modes is one of the dependencies of ComfyUI_LayerStyle which is not properly installed during install process when pulling the node through the cm-cli/comfy-cli 

Although this could be a question for the comfy-cli or manager repos, do you guys know a way to not use the ComfyUI_MaraScott_Nodes ? It is a really nice node package but I feel like it is way too big for my needs and I would like to be able to use the was_node_suite. 
Also I am curious about what drove the decision to package third party node packages in this one instead of considering them as an external dependency. 

Thank you !

**Comment by GalaxyTimeMachine** [comment]
I'm getting the same.
